#!/usr/bin/env python3
"""Regenerate kernel/font8x16.c from a VGA BIOS ROM's CP437 8x16 font.

The ROM font is the same one VGA text mode uses, so the framebuffer console
matches text mode exactly and CP437 box drawing (used by fm/play) works.

The table is located by anchoring on glyph 0xDB (full block, 16 bytes of 0xFF)
and then verified two ways: structurally (NUL/space/0xFF blank, letters not
blank) and, when a PSF console font is available, by comparing the ASCII range
against it. Both checks must pass before anything is written.

Usage: genfont.py [--rom PATH] [--psf PATH] [--check]
"""

import argparse
import gzip
import os
import re
import struct
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(HERE, "kernel", "font8x16.c")

DEFAULT_ROMS = [
    "/usr/share/seabios/vgabios.bin",
    "/usr/share/seabios/vgabios-stdvga.bin",
    "/usr/share/seabios/vgabios-bochs-display.bin",
    "/usr/share/qemu/vgabios.bin",
]

DEFAULT_PSFS = [
    "/usr/share/consolefonts/Lat15-VGA16.psf.gz",
    "/usr/share/consolefonts/Lat2-VGA16.psf.gz",
]

GLYPH_H = 16
FULL_BLOCK = 0xDB


def read_maybe_gz(path):
    with open(path, "rb") as fh:
        head = fh.read(2)
        fh.seek(0)
        data = fh.read()
    if head == b"\x1f\x8b":
        return gzip.decompress(data)
    return data


def load_psf(path):
    """Return {code: [16 bytes]} for an 8x16 PSF1/PSF2 font."""
    data = read_maybe_gz(path)

    if data[:2] == b"\x36\x04":                       # PSF1
        mode, charsize = data[2], data[3]
        if charsize != GLYPH_H:
            return None
        count = 512 if mode & 0x01 else 256
        body = data[4:4 + count * charsize]
    elif data[:4] == b"\x72\xb5\x4a\x86":             # PSF2
        (_, _, _, length, charsize, height, width) = struct.unpack(
            "<IIIIIII", data[4:32])
        if height != GLYPH_H or width != 8:
            return None
        count = length
        body = data[32:32 + count * charsize]
        charsize = charsize
    else:
        return None

    return {c: list(body[c * GLYPH_H:(c + 1) * GLYPH_H]) for c in range(count)}


def structurally_valid(table):
    def blank(c):
        return not any(table[c * GLYPH_H:(c + 1) * GLYPH_H])

    if not (blank(0x00) and blank(0x20) and blank(0xFF)):
        return False
    if any(blank(c) for c in list(range(0x41, 0x5B)) + list(range(0x61, 0x7B))):
        return False
    if any(b != 0xFF for b in table[FULL_BLOCK * GLYPH_H:(FULL_BLOCK + 1) * GLYPH_H]):
        return False
    return True


def find_table(rom):
    """Locate the 4096-byte CP437 8x16 font, anchored on the full-block glyph."""
    hits = []
    start = 0
    while True:
        pos = rom.find(b"\xff" * GLYPH_H, start)
        if pos < 0:
            break
        base = pos - FULL_BLOCK * GLYPH_H
        if base >= 0 and base + 4096 <= len(rom):
            table = rom[base:base + 4096]
            if structurally_valid(table):
                hits.append((base, table))
        start = pos + 1
    return hits


# The Debian VGA16 PSFs are 7-pixel-wide redraws of the 8-pixel IBM originals,
# so a correctly located table still differs on a dozen or so wide glyphs
# (M, W, T, 0, ...). Require a strong majority, not an exact match.
PSF_MIN_RATIO = 0.75


def psf_agreement(table, psf):
    """How many ASCII glyphs match the reference font."""
    same = total = 0
    for c in range(0x20, 0x7F):
        if c not in psf:
            continue
        total += 1
        if list(table[c * GLYPH_H:(c + 1) * GLYPH_H]) == psf[c]:
            same += 1
    return same, total


def emit(table, source):
    lines = [
        f"/* Generated by scripts/genfont.py from {source}.",
        " * CP437 8x16, 16 bytes per glyph, indexed directly by character code.",
        " * Do not edit by hand - rerun the script instead. */",
        "",
        '#include "font8x16.h"',
        "",
        "const uint8_t font8x16[256 * 16] = {",
    ]
    for c in range(256):
        glyph = table[c * GLYPH_H:(c + 1) * GLYPH_H]
        body = ",".join(f"0x{b:02x}" for b in glyph)
        lines.append(f"    /* 0x{c:02x} */ {body},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def load_current():
    src = open(OUT).read()
    body = src[src.index("{") + 1: src.rindex("}")]
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    vals = [int(v, 16) for v in re.findall(r"0x([0-9a-fA-F]{2})", body)]
    return bytes(vals)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom", action="append", default=[])
    ap.add_argument("--psf", action="append", default=[])
    ap.add_argument("--check", action="store_true",
                    help="validate kernel/font8x16.c instead of rewriting it")
    args = ap.parse_args()

    psf = None
    psf_src = None
    for path in args.psf or DEFAULT_PSFS:
        if os.path.exists(path):
            psf = load_psf(path)
            if psf:
                psf_src = path
                break

    if args.check:
        table = load_current()
        ok = structurally_valid(table)
        print(f"{OUT}: structural check {'PASS' if ok else 'FAIL'}")
        if psf:
            same, total = psf_agreement(table, psf)
            print(f"ASCII vs {os.path.basename(psf_src)}: {same}/{total} glyphs match")
            ok = ok and same >= total * PSF_MIN_RATIO
        return 0 if ok else 1

    for path in args.rom or DEFAULT_ROMS:
        if not os.path.exists(path):
            continue
        rom = open(path, "rb").read()
        hits = find_table(rom)
        if not hits:
            print(f"{path}: no 8x16 CP437 font table found")
            continue

        best = None
        for base, table in hits:
            score = psf_agreement(table, psf) if psf else (0, 0)
            if best is None or score[0] > best[2][0]:
                best = (base, table, score)

        base, table, (same, total) = best
        if psf and total and same < total * PSF_MIN_RATIO:
            print(f"{path}: table at {base:#x} disagrees with "
                  f"{os.path.basename(psf_src)} ({same}/{total}) — refusing")
            continue

        with open(OUT, "w") as fh:
            fh.write(emit(table, f"{os.path.basename(path)} at offset {base:#x}"))
        print(f"wrote {OUT}")
        print(f"  source: {path} offset {base:#x}")
        if psf:
            print(f"  ASCII vs {os.path.basename(psf_src)}: {same}/{total} match")
        blank = [c for c in range(256)
                 if not any(table[c * GLYPH_H:(c + 1) * GLYPH_H])]
        print(f"  blank glyphs: {[hex(c) for c in blank]}")
        return 0

    print("no usable VGA BIOS ROM found")
    return 1


if __name__ == "__main__":
    sys.exit(main())
